---
- hosts: gluster
  become: yes

  vars_files:
    - vars.yml

  tasks: # show all the hosts in the current play
    - name: Debug node name
      debug:
        msg: "{{ item }} {{ hostvars[item].ansible_facts.hostname }}"
      loop: "{{ ansible_play_batch }}"

    - name: Create hosts test file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ hostvars[item].ansible_facts.hostname }}$'
        line: "{{ item }} {{ hostvars[item].ansible_facts.hostname }}"
        state: present
      loop: "{{ ansible_play_batch }}"

   # show all the hosts in the current play
    - name: Debug items message
      debug:
        msg: ""
              #msg: "{{ hostvars }} "
